import type { Feature } from '../composer.js';

export function databaseFeature(config: {
  orm: 'prisma' | 'drizzle';
  projectName: string;
  includeAuth: boolean;
}): Feature {
  if (config.orm === 'prisma') {
    return prismaFeature(config.projectName, config.includeAuth);
  }
  return drizzleFeature(config.projectName, config.includeAuth);
}

// ─── Prisma ──────────────────────────────────────────────────────────────────

function prismaFeature(projectName: string, includeAuth: boolean): Feature {
  return {
    name: 'database-prisma',
    files: [
      {
        path: 'db/schema.prisma',
        content: `// Prisma schema for ${projectName}
// Docs: https://pris.ly/d/prisma-schema

generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "windows", "debian-openssl-3.0.x", "debian-openssl-1.1.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id        Int      @id @default(autoincrement())
  externalId String   @unique
  email     String?
  name      String?
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  items Item[]
}

model Item {
  id          Int      @id @default(autoincrement())
  title       String
  description String?
  completed   Boolean  @default(false)
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt

  userId Int
  user   User @relation(fields: [userId], references: [id])
}
`,
      },
      {
        path: 'db/migrations/migration_lock.toml',
        content: `# Please do not edit this file manually
# It should be added in your version-control system (e.g., Git)
provider = "postgresql"
`,
      },
      {
        path: 'db/migrations/0001_init/migration.sql',
        content: `-- CreateTable
CREATE TABLE "User" (
    "id" SERIAL NOT NULL,
    "externalId" TEXT NOT NULL,
    "email" TEXT,
    "name" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Item" (
    "id" SERIAL NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "completed" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "userId" INTEGER NOT NULL,

    CONSTRAINT "Item_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_externalId_key" ON "User"("externalId");

-- AddForeignKey
ALTER TABLE "Item" ADD CONSTRAINT "Item_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
`,
      },
      {
        path: 'db/seed.ts',
        content: `import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main(): Promise<void> {
  console.log('🌱 Seeding database...');

  const alice = await prisma.user.upsert({
    where: { externalId: 'sample-alice' },
    update: {
      email: 'alice@example.com',
      name: 'Alice',
    },
    create: {
      externalId: 'sample-alice',
      email: 'alice@example.com',
      name: 'Alice',
      items: {
        create: [
          { title: 'Create your app', description: 'Choose your frontend framework, ORM, and auth preferences to generate your Azure project.', completed: true },
          { title: 'Develop locally', description: 'Run your full stack locally with Docker PostgreSQL, SWA CLI, and hot reload across frontend and API.', completed: true },
        ],
      },
    },
  });

  const bob = await prisma.user.upsert({
    where: { externalId: 'sample-bob' },
    update: {
      email: 'bob@example.com',
      name: 'Bob',
    },
    create: {
      externalId: 'sample-bob',
      email: 'bob@example.com',
      name: 'Bob',
      items: {
        create: [
          { title: 'Deploy to Azure', description: 'Provision infrastructure and deploy your app in one command with azd up.', completed: false },
          { title: 'Set up CI/CD', description: 'Configure GitHub Actions with OIDC to auto-deploy on push with azd pipeline config.', completed: false },
        ],
      },
    },
  });

  console.log(\`✅ Seeded \${alice.name} and \${bob.name}\`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
`,
      },
      {
        path: 'src/api/src/lib/db.ts',
        content: `import { PrismaClient } from '@prisma/client';

let _prisma: PrismaClient | null = null;

export function getPrisma(): PrismaClient {
  if (!_prisma) {
    _prisma = new PrismaClient();
  }
  return _prisma;
}

export default { get client() { return getPrisma(); } };
`,
      },
      {
        path: 'src/api/src/functions/items.ts',
        content: prismaItemsTemplate(includeAuth),
      },
      {
        path: 'scripts/sync-prisma-client.mjs',
        content: `#!/usr/bin/env node
/**
 * sync-prisma-client.mjs
 *
 * Copies the generated Prisma client from the repo root into the
 * Azure Functions sub-project so \`func start\` can resolve it.
 *
 * Run from src/api/:  node ../../scripts/sync-prisma-client.mjs
 */
import { cpSync, existsSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');

const pairs = [
  ['node_modules/@prisma/client', 'src/api/node_modules/@prisma/client'],
  ['node_modules/.prisma',        'src/api/node_modules/.prisma'],
];

for (const [src, dest] of pairs) {
  const srcPath  = resolve(repoRoot, src);
  const destPath = resolve(repoRoot, dest);

  if (!existsSync(srcPath)) {
    console.warn(\`⚠  source not found, skipping: \${srcPath}\`);
    continue;
  }

  mkdirSync(dirname(destPath), { recursive: true });
  cpSync(srcPath, destPath, { recursive: true, force: true });
  console.log(\`✔  \${src} → \${dest}\`);
}
`,
      },
      {
        path: 'scripts/slim-swa-api-package.mjs',
        content: `#!/usr/bin/env node
/**
 * slim-swa-api-package.mjs
 *
 * Trims non-runtime Prisma artefacts from src/api so SWA deploy
 * doesn't exceed the 100 MB limit.
 *
 * Run from repo root:  node scripts/slim-swa-api-package.mjs
 */
import { rmSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');
const apiDir   = resolve(repoRoot, 'src/api');

const removePaths = [
  'node_modules/.prisma/client/libquery_engine-debian-openssl-3.0.x.so.node',
  'node_modules/.prisma/client/libquery_engine-windows.dll.node',
  'node_modules/@prisma/engines',
  'node_modules/prisma',
  'node_modules/@prisma/client/generator-build',
  // Dev dependencies \u2013 not needed at runtime
  'node_modules/typescript',
  'node_modules/@types',
];

for (const rel of removePaths) {
  const full = resolve(apiDir, rel);
  if (existsSync(full)) {
    rmSync(full, { recursive: true, force: true });
    console.log(\`✔  removed \${rel}\`);
  }
}
`,
      },
    ],
    dependencies: {
      '@prisma/client': '^6.2.0',
    },
    devDependencies: {
      prisma: '^6.2.0',
      tsx: '^4.19.0',
    },
    scripts: {
      'db:generate': 'prisma generate --schema=db/schema.prisma',
      'db:migrate': 'prisma migrate deploy --schema=db/schema.prisma && prisma generate --schema=db/schema.prisma',
      'db:migrate:dev': 'prisma migrate dev --schema=db/schema.prisma',
      'db:seed': 'tsx --env-file=.env db/seed.ts',
      'db:seed:azure': 'pwsh scripts/seed.ps1',
      'db:seed:azure:posix': 'bash scripts/seed.sh',
    },
  };
}

// ─── Drizzle ─────────────────────────────────────────────────────────────────

function drizzleFeature(projectName: string, includeAuth: boolean): Feature {
  return {
    name: 'database-drizzle',
    files: [
      {
        path: 'src/api/src/db/schema.ts',
        content: `// Drizzle schema for ${projectName}
// Docs: https://orm.drizzle.team/docs/sql-schema-declaration

import { serial, varchar, text, boolean, timestamp, integer, pgTable } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  externalId: varchar('external_id', { length: 255 }).notNull().unique(),
  email: varchar('email', { length: 255 }),
  name: varchar('name', { length: 255 }),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

export const items = pgTable('items', {
  id: serial('id').primaryKey(),
  title: varchar('title', { length: 255 }).notNull(),
  description: text('description'),
  completed: boolean('completed').default(false).notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
  userId: integer('user_id')
    .notNull()
    .references(() => users.id),
});
`,
      },
      {
        path: 'src/api/src/db/seed.ts',
        content: `import { drizzle } from 'drizzle-orm/node-postgres';
import { Pool } from 'pg';
import * as schema from './schema.js';

async function main(): Promise<void> {
  const pool = new Pool({ connectionString: process.env['DATABASE_URL'] });
  const db = drizzle(pool, { schema });

  console.log('🌱 Seeding database...');

  const [alice] = await db
    .insert(schema.users)
    .values({ externalId: 'sample-alice', email: 'alice@example.com', name: 'Alice' })
    .onConflictDoNothing()
    .returning();

  const [bob] = await db
    .insert(schema.users)
    .values({ externalId: 'sample-bob', email: 'bob@example.com', name: 'Bob' })
    .onConflictDoNothing()
    .returning();

  if (alice) {
    await db.insert(schema.items).values([
      { title: 'Create your app', description: 'Choose your frontend framework, ORM, and auth preferences to generate your Azure project.', completed: false, userId: alice.id },
      { title: 'Develop locally', description: 'Run your full stack locally with Docker PostgreSQL, SWA CLI, and hot reload across frontend and API.', completed: false, userId: alice.id },
    ]).onConflictDoNothing();
  }

  if (bob) {
    await db.insert(schema.items).values([
      { title: 'Deploy to Azure', description: 'Provision infrastructure and deploy your app in one command with azd up.', completed: false, userId: bob.id },
      { title: 'Set up CI/CD', description: 'Configure GitHub Actions to auto-deploy on push with azd pipeline config.', completed: false, userId: bob.id },
    ]).onConflictDoNothing();
  }

  console.log('✅ Seeded sample users and items');
  await pool.end();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
`,
      },
      {
        path: 'drizzle.config.ts',
        content: `import { defineConfig } from 'drizzle-kit';

export default defineConfig({
  schema: './src/api/src/db/schema.ts',
  out: './db/migrations',
  dialect: 'postgresql',
  dbCredentials: {
    url: process.env['DATABASE_URL']!,
  },
});
`,
      },
      {
        path: 'db/migrations/0000_initial.sql',
        content: `CREATE TABLE "items" (
	"id" serial PRIMARY KEY NOT NULL,
	"title" varchar(255) NOT NULL,
	"description" text,
	"completed" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"user_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"external_id" varchar(255) NOT NULL,
	"email" varchar(255),
	"name" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "users_external_id_unique" UNIQUE("external_id")
);
--> statement-breakpoint
ALTER TABLE "items" ADD CONSTRAINT "items_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
`,
      },
      {
        path: 'db/migrations/meta/_journal.json',
        content: `{
  "version": "7",
  "dialect": "postgresql",
  "entries": [
    {
      "idx": 0,
      "version": "7",
      "when": 1735689600000,
      "tag": "0000_initial",
      "breakpoints": true
    }
  ]
}
`,
      },
      {
        path: 'db/migrations/meta/0000_snapshot.json',
        content: `{
  "id": "3891187f-089d-4875-814b-7bb4ef34ee02",
  "prevId": "00000000-0000-0000-0000-000000000000",
  "version": "7",
  "dialect": "postgresql",
  "tables": {
    "public.items": {
      "name": "items",
      "schema": "",
      "columns": {
        "id": {
          "name": "id",
          "type": "serial",
          "primaryKey": true,
          "notNull": true
        },
        "title": {
          "name": "title",
          "type": "varchar(255)",
          "primaryKey": false,
          "notNull": true
        },
        "description": {
          "name": "description",
          "type": "text",
          "primaryKey": false,
          "notNull": false
        },
        "completed": {
          "name": "completed",
          "type": "boolean",
          "primaryKey": false,
          "notNull": true,
          "default": false
        },
        "created_at": {
          "name": "created_at",
          "type": "timestamp",
          "primaryKey": false,
          "notNull": true,
          "default": "now()"
        },
        "updated_at": {
          "name": "updated_at",
          "type": "timestamp",
          "primaryKey": false,
          "notNull": true,
          "default": "now()"
        },
        "user_id": {
          "name": "user_id",
          "type": "integer",
          "primaryKey": false,
          "notNull": true
        }
      },
      "indexes": {},
      "foreignKeys": {
        "items_user_id_users_id_fk": {
          "name": "items_user_id_users_id_fk",
          "tableFrom": "items",
          "tableTo": "users",
          "columnsFrom": [
            "user_id"
          ],
          "columnsTo": [
            "id"
          ],
          "onDelete": "no action",
          "onUpdate": "no action"
        }
      },
      "compositePrimaryKeys": {},
      "uniqueConstraints": {},
      "policies": {},
      "checkConstraints": {},
      "isRLSEnabled": false
    },
    "public.users": {
      "name": "users",
      "schema": "",
      "columns": {
        "id": {
          "name": "id",
          "type": "serial",
          "primaryKey": true,
          "notNull": true
        },
        "external_id": {
          "name": "external_id",
          "type": "varchar(255)",
          "primaryKey": false,
          "notNull": true
        },
        "email": {
          "name": "email",
          "type": "varchar(255)",
          "primaryKey": false,
          "notNull": false
        },
        "name": {
          "name": "name",
          "type": "varchar(255)",
          "primaryKey": false,
          "notNull": false
        },
        "created_at": {
          "name": "created_at",
          "type": "timestamp",
          "primaryKey": false,
          "notNull": true,
          "default": "now()"
        },
        "updated_at": {
          "name": "updated_at",
          "type": "timestamp",
          "primaryKey": false,
          "notNull": true,
          "default": "now()"
        }
      },
      "indexes": {},
      "foreignKeys": {},
      "compositePrimaryKeys": {},
      "uniqueConstraints": {
        "users_external_id_unique": {
          "name": "users_external_id_unique",
          "nullsNotDistinct": false,
          "columns": [
            "external_id"
          ]
        }
      },
      "policies": {},
      "checkConstraints": {},
      "isRLSEnabled": false
    }
  },
  "enums": {},
  "schemas": {},
  "sequences": {},
  "roles": {},
  "policies": {},
  "views": {},
  "_meta": {
    "columns": {},
    "schemas": {},
    "tables": {}
  }
}
`,
      },
      {
        path: 'src/api/src/lib/db.ts',
        content: `import { drizzle } from 'drizzle-orm/node-postgres';
import { Pool } from 'pg';
import * as schema from '../db/schema.js';

const pool = new Pool({
  connectionString: process.env['DATABASE_URL'],
});

export const db = drizzle(pool, { schema });
export default db;
`,
      },
      {
        path: 'src/api/src/functions/items.ts',
        content: drizzleItemsTemplate(includeAuth),
      },
    ],
    dependencies: {},
    devDependencies: {
      'drizzle-orm': '^0.45.2',
      pg: '^8.13.0',
      'drizzle-kit': '^0.30.0',
      '@types/pg': '^8.11.0',
      tsx: '^4.19.0',
    },
    scripts: {
      'db:generate': 'drizzle-kit generate',
      'db:migrate': 'drizzle-kit migrate',
      'db:seed': 'tsx --env-file=.env src/api/src/db/seed.ts',
      'db:push': 'drizzle-kit push',
    },
  };
}

function prismaItemsTemplate(includeAuth: boolean): string {
  if (!includeAuth) {
    return `import {
  app,
  HttpRequest,
  HttpResponseInit,
  InvocationContext,
} from '@azure/functions';
import { getPrisma } from '../lib/db.js';

// GET /api/items
app.http('listItems', {
  methods: ['GET'],
  authLevel: 'anonymous',
  route: 'items',
  handler: async (
    request: HttpRequest,
    context: InvocationContext
  ): Promise<HttpResponseInit> => {
    const prisma = getPrisma();
    const items = await prisma.item.findMany({ orderBy: { createdAt: 'desc' } });
    return { jsonBody: items };
  },
});

// GET /api/items/{id}
app.http('getItem', {
  methods: ['GET'],
  authLevel: 'anonymous',
  route: 'items/{id}',
  handler: async (
    request: HttpRequest,
    context: InvocationContext
  ): Promise<HttpResponseInit> => {
    const id = Number(request.params.id);
    if (isNaN(id)) {
      return { status: 400, jsonBody: { error: 'Invalid item ID' } };
    }

    const prisma = getPrisma();
    const item = await prisma.item.findUnique({ where: { id } });
    if (!item) {
      return { status: 404, jsonBody: { error: 'Item not found' } };
    }

    return { jsonBody: item };
  },
});

// POST /api/items
app.http('createItem', {
  methods: ['POST'],
  authLevel: 'anonymous',
  route: 'items',
  handler: async (
    request: HttpRequest,
    context: InvocationContext
  ): Promise<HttpResponseInit> => {
    const body = (await request.json()) as {
      title?: string;
      description?: string;
      userId?: number;
    };

    if (!body.title) {
      return { status: 400, jsonBody: { error: 'Title is required' } };
    }
    if (!body.userId) {
      return { status: 400, jsonBody: { error: 'userId is required' } };
    }

    const prisma = getPrisma();
    const item = await prisma.item.create({
      data: {
        title: body.title,
        description: body.description ?? null,
        userId: body.userId,
      },
    });

    return { status: 201, jsonBody: item };
  },
});

// PUT /api/items/{id}
app.http('updateItem', {
  methods: ['PUT'],
  authLevel: 'anonymous',
  route: 'items/{id}',
  handler: async (
    request: HttpRequest,
    context: InvocationContext
  ): Promise<HttpResponseInit> => {
    const id = Number(request.params.id);
    if (isNaN(id)) {
      return { status: 400, jsonBody: { error: 'Invalid item ID' } };
    }

    const prisma = getPrisma();
    const existing = await prisma.item.findUnique({ where: { id } });
    if (!existing) {
      return { status: 404, jsonBody: { error: 'Item not found' } };
    }

    const body = (await request.json()) as {
      title?: string;
      description?: string;
      completed?: boolean;
    };

    const item = await prisma.item.update({
      where: { id },
      data: {
        ...(body.title !== undefined && { title: body.title }),
        ...(body.description !== undefined && { description: body.description }),
        ...(body.completed !== undefined && { completed: body.completed }),
      },
    });

    return { jsonBody: item };
  },
});

// DELETE /api/items/{id}
app.http('deleteItem', {
  methods: ['DELETE'],
  authLevel: 'anonymous',
  route: 'items/{id}',
  handler: async (
    request: HttpRequest,
    context: InvocationContext
  ): Promise<HttpResponseInit> => {
    const id = Number(request.params.id);
    if (isNaN(id)) {
      return { status: 400, jsonBody: { error: 'Invalid item ID' } };
    }

    const prisma = getPrisma();
    const existing = await prisma.item.findUnique({ where: { id } });
    if (!existing) {
      return { status: 404, jsonBody: { error: 'Item not found' } };
    }

    await prisma.item.delete({ where: { id } });
    return { status: 204 };
  },
});
`;
  }

  return `import {
  app,
  HttpRequest,
  HttpResponseInit,
  InvocationContext,
} from '@azure/functions';
import { getPrisma } from '../lib/db.js';
import { requireAuth } from '../lib/auth.js';

function normalizeUserDetails(userDetails: string): { email: string | null; name: string | null } {
  const trimmed = userDetails.trim();
  return {
    email: trimmed.includes('@') ? trimmed.toLowerCase() : null,
    name: trimmed.length > 0 ? trimmed : null,
  };
}

async function ensureCurrentUser(request: HttpRequest) {
  const authUser = requireAuth(request);
  const prisma = getPrisma();
  const profile = normalizeUserDetails(authUser.userDetails);

  return prisma.user.upsert({
    where: { externalId: authUser.userId },
    update: {
      email: profile.email,
      name: profile.name,
    },
    create: {
      externalId: authUser.userId,
      email: profile.email,
      name: profile.name,
    },
  });
}

// GET /api/items
app.http('listItems', {
  methods: ['GET'],
  authLevel: 'anonymous',
  route: 'items',
  handler: async (
    request: HttpRequest,
    context: InvocationContext
  ): Promise<HttpResponseInit> => {
    requireAuth(request);
    const prisma = getPrisma();
    const items = await prisma.item.findMany({ orderBy: { createdAt: 'desc' } });
    return { jsonBody: items };
  },
});

// GET /api/items/{id}
app.http('getItem', {
  methods: ['GET'],
  authLevel: 'anonymous',
  route: 'items/{id}',
  handler: async (
    request: HttpRequest,
    context: InvocationContext
  ): Promise<HttpResponseInit> => {
    const id = Number(request.params.id);
    if (isNaN(id)) {
      return { status: 400, jsonBody: { error: 'Invalid item ID' } };
    }

    requireAuth(request);
    const prisma = getPrisma();
    const item = await prisma.item.findUnique({ where: { id } });
    if (!item) {
      return { status: 404, jsonBody: { error: 'Item not found' } };
    }

    return { jsonBody: item };
  },
});

// POST /api/items
app.http('createItem', {
  methods: ['POST'],
  authLevel: 'anonymous',
  route: 'items',
  handler: async (
    request: HttpRequest,
    context: InvocationContext
  ): Promise<HttpResponseInit> => {
    const currentUser = await ensureCurrentUser(request);
    const body = (await request.json()) as {
      title?: string;
      description?: string;
    };

    if (!body.title) {
      return { status: 400, jsonBody: { error: 'Title is required' } };
    }

    const prisma = getPrisma();
    const item = await prisma.item.create({
      data: {
        title: body.title,
        description: body.description ?? null,
        userId: currentUser.id,
      },
    });

    return { status: 201, jsonBody: item };
  },
});

// PUT /api/items/{id}
app.http('updateItem', {
  methods: ['PUT'],
  authLevel: 'anonymous',
  route: 'items/{id}',
  handler: async (
    request: HttpRequest,
    context: InvocationContext
  ): Promise<HttpResponseInit> => {
    const id = Number(request.params.id);
    if (isNaN(id)) {
      return { status: 400, jsonBody: { error: 'Invalid item ID' } };
    }

    requireAuth(request);
    const prisma = getPrisma();
    const existing = await prisma.item.findUnique({ where: { id } });
    if (!existing) {
      return { status: 404, jsonBody: { error: 'Item not found' } };
    }

    const body = (await request.json()) as {
      title?: string;
      description?: string;
      completed?: boolean;
    };

    const item = await prisma.item.update({
      where: { id },
      data: {
        ...(body.title !== undefined && { title: body.title }),
        ...(body.description !== undefined && { description: body.description }),
        ...(body.completed !== undefined && { completed: body.completed }),
      },
    });

    return { jsonBody: item };
  },
});

// DELETE /api/items/{id}
app.http('deleteItem', {
  methods: ['DELETE'],
  authLevel: 'anonymous',
  route: 'items/{id}',
  handler: async (
    request: HttpRequest,
    context: InvocationContext
  ): Promise<HttpResponseInit> => {
    const id = Number(request.params.id);
    if (isNaN(id)) {
      return { status: 400, jsonBody: { error: 'Invalid item ID' } };
    }

    requireAuth(request);
    const prisma = getPrisma();
    const existing = await prisma.item.findUnique({ where: { id } });
    if (!existing) {
      return { status: 404, jsonBody: { error: 'Item not found' } };
    }

    await prisma.item.delete({ where: { id } });
    return { status: 204 };
  },
});
`;
}

function drizzleItemsTemplate(includeAuth: boolean): string {
  if (!includeAuth) {
    return `import {
  app,
  HttpRequest,
  HttpResponseInit,
  InvocationContext,
} from '@azure/functions';
import { eq } from 'drizzle-orm';
import db from '../lib/db.js';
import { items } from '../db/schema.js';

// GET /api/items
app.http('listItems', {
  methods: ['GET'],
  authLevel: 'anonymous',
  route: 'items',
  handler: async (
    request: HttpRequest,
    context: InvocationContext
  ): Promise<HttpResponseInit> => {
    const rows = await db.select().from(items).orderBy(items.createdAt);
    return { jsonBody: rows };
  },
});

// GET /api/items/{id}
app.http('getItem', {
  methods: ['GET'],
  authLevel: 'anonymous',
  route: 'items/{id}',
  handler: async (
    request: HttpRequest,
    context: InvocationContext
  ): Promise<HttpResponseInit> => {
    const id = Number(request.params.id);
    if (isNaN(id)) {
      return { status: 400, jsonBody: { error: 'Invalid item ID' } };
    }

    const [item] = await db.select().from(items).where(eq(items.id, id));
    if (!item) {
      return { status: 404, jsonBody: { error: 'Item not found' } };
    }

    return { jsonBody: item };
  },
});

// POST /api/items
app.http('createItem', {
  methods: ['POST'],
  authLevel: 'anonymous',
  route: 'items',
  handler: async (
    request: HttpRequest,
    context: InvocationContext
  ): Promise<HttpResponseInit> => {
    const body = (await request.json()) as {
      title?: string;
      description?: string;
      userId?: number;
    };

    if (!body.title) {
      return { status: 400, jsonBody: { error: 'Title is required' } };
    }
    if (!body.userId) {
      return { status: 400, jsonBody: { error: 'userId is required' } };
    }

    const [item] = await db
      .insert(items)
      .values({
        title: body.title,
        description: body.description ?? null,
        userId: body.userId,
      })
      .returning();

    return { status: 201, jsonBody: item };
  },
});

// PUT /api/items/{id}
app.http('updateItem', {
  methods: ['PUT'],
  authLevel: 'anonymous',
  route: 'items/{id}',
  handler: async (
    request: HttpRequest,
    context: InvocationContext
  ): Promise<HttpResponseInit> => {
    const id = Number(request.params.id);
    if (isNaN(id)) {
      return { status: 400, jsonBody: { error: 'Invalid item ID' } };
    }

    const [existing] = await db.select().from(items).where(eq(items.id, id));
    if (!existing) {
      return { status: 404, jsonBody: { error: 'Item not found' } };
    }

    const body = (await request.json()) as {
      title?: string;
      description?: string;
      completed?: boolean;
    };

    const [updated] = await db
      .update(items)
      .set({
        ...(body.title !== undefined && { title: body.title }),
        ...(body.description !== undefined && { description: body.description }),
        ...(body.completed !== undefined && { completed: body.completed }),
        updatedAt: new Date(),
      })
      .where(eq(items.id, id))
      .returning();

    return { jsonBody: updated };
  },
});

// DELETE /api/items/{id}
app.http('deleteItem', {
  methods: ['DELETE'],
  authLevel: 'anonymous',
  route: 'items/{id}',
  handler: async (
    request: HttpRequest,
    context: InvocationContext
  ): Promise<HttpResponseInit> => {
    const id = Number(request.params.id);
    if (isNaN(id)) {
      return { status: 400, jsonBody: { error: 'Invalid item ID' } };
    }

    const [existing] = await db.select().from(items).where(eq(items.id, id));
    if (!existing) {
      return { status: 404, jsonBody: { error: 'Item not found' } };
    }

    await db.delete(items).where(eq(items.id, id));
    return { status: 204 };
  },
});
`;
  }

  return `import {
  app,
  HttpRequest,
  HttpResponseInit,
  InvocationContext,
} from '@azure/functions';
import { eq } from 'drizzle-orm';
import db from '../lib/db.js';
import { items, users } from '../db/schema.js';
import { requireAuth } from '../lib/auth.js';

function normalizeUserDetails(userDetails: string): { email: string | null; name: string | null } {
  const trimmed = userDetails.trim();
  return {
    email: trimmed.includes('@') ? trimmed.toLowerCase() : null,
    name: trimmed.length > 0 ? trimmed : null,
  };
}

async function ensureCurrentUser(request: HttpRequest) {
  const authUser = requireAuth(request);
  const profile = normalizeUserDetails(authUser.userDetails);

  const [user] = await db
    .insert(users)
    .values({
      externalId: authUser.userId,
      email: profile.email,
      name: profile.name,
    })
    .onConflictDoUpdate({
      target: users.externalId,
      set: {
        email: profile.email,
        name: profile.name,
        updatedAt: new Date(),
      },
    })
    .returning();

  return user;
}

// GET /api/items
app.http('listItems', {
  methods: ['GET'],
  authLevel: 'anonymous',
  route: 'items',
  handler: async (
    request: HttpRequest,
    context: InvocationContext
  ): Promise<HttpResponseInit> => {
    requireAuth(request);
    const rows = await db
      .select()
      .from(items)
      .orderBy(items.createdAt);
    return { jsonBody: rows };
  },
});

// GET /api/items/{id}
app.http('getItem', {
  methods: ['GET'],
  authLevel: 'anonymous',
  route: 'items/{id}',
  handler: async (
    request: HttpRequest,
    context: InvocationContext
  ): Promise<HttpResponseInit> => {
    const id = Number(request.params.id);
    if (isNaN(id)) {
      return { status: 400, jsonBody: { error: 'Invalid item ID' } };
    }

    requireAuth(request);
    const [item] = await db.select().from(items).where(eq(items.id, id));
    if (!item) {
      return { status: 404, jsonBody: { error: 'Item not found' } };
    }

    return { jsonBody: item };
  },
});

// POST /api/items
app.http('createItem', {
  methods: ['POST'],
  authLevel: 'anonymous',
  route: 'items',
  handler: async (
    request: HttpRequest,
    context: InvocationContext
  ): Promise<HttpResponseInit> => {
    const currentUser = await ensureCurrentUser(request);
    const body = (await request.json()) as {
      title?: string;
      description?: string;
    };

    if (!body.title) {
      return { status: 400, jsonBody: { error: 'Title is required' } };
    }

    const [item] = await db
      .insert(items)
      .values({
        title: body.title,
        description: body.description ?? null,
        userId: currentUser.id,
      })
      .returning();

    return { status: 201, jsonBody: item };
  },
});

// PUT /api/items/{id}
app.http('updateItem', {
  methods: ['PUT'],
  authLevel: 'anonymous',
  route: 'items/{id}',
  handler: async (
    request: HttpRequest,
    context: InvocationContext
  ): Promise<HttpResponseInit> => {
    const id = Number(request.params.id);
    if (isNaN(id)) {
      return { status: 400, jsonBody: { error: 'Invalid item ID' } };
    }

    requireAuth(request);
    const [existing] = await db.select().from(items).where(eq(items.id, id));
    if (!existing) {
      return { status: 404, jsonBody: { error: 'Item not found' } };
    }

    const body = (await request.json()) as {
      title?: string;
      description?: string;
      completed?: boolean;
    };

    const [updated] = await db
      .update(items)
      .set({
        ...(body.title !== undefined && { title: body.title }),
        ...(body.description !== undefined && { description: body.description }),
        ...(body.completed !== undefined && { completed: body.completed }),
        updatedAt: new Date(),
      })
      .where(eq(items.id, id))
      .returning();

    return { jsonBody: updated };
  },
});

// DELETE /api/items/{id}
app.http('deleteItem', {
  methods: ['DELETE'],
  authLevel: 'anonymous',
  route: 'items/{id}',
  handler: async (
    request: HttpRequest,
    context: InvocationContext
  ): Promise<HttpResponseInit> => {
    const id = Number(request.params.id);
    if (isNaN(id)) {
      return { status: 400, jsonBody: { error: 'Invalid item ID' } };
    }

    requireAuth(request);
    const [existing] = await db.select().from(items).where(eq(items.id, id));
    if (!existing) {
      return { status: 404, jsonBody: { error: 'Item not found' } };
    }

    await db.delete(items).where(eq(items.id, id));
    return { status: 204 };
  },
});
`;
}
