import type { Feature } from '../composer.js';
import type { ProjectConfig } from '../index.js';
import { pmRun, pmInstall } from '../utils.js';

export function sveltekitFeature(config: ProjectConfig): Feature {
  const { projectName } = config;

  return {
    name: 'sveltekit',
    files: [
      {
        path: 'src/web/package.json',
        content:
          JSON.stringify(
            {
              name: `${projectName}-web`,
              version: '0.1.1',
              private: true,
              type: 'module',
              scripts: {
                dev: 'vite dev',
                build: 'vite build',
                preview: 'vite preview',
                check: 'svelte-kit sync && svelte-check --tsconfig ./tsconfig.json',
              },
              devDependencies: {
                '@sveltejs/adapter-static': '^3.0.0',
                '@sveltejs/kit': '^2.15.0',
                '@sveltejs/vite-plugin-svelte': '^5.0.0',
                svelte: '^5.0.0',
                'svelte-check': '^4.0.0',
                typescript: '^5.8.0',
                vite: '^6.3.0',
                ...(config.includeTailwind ? {
                  tailwindcss: '^4.0.0',
                  '@tailwindcss/postcss': '^4.0.0',
                } : {}),
              },
            },
            null,
            2
          ) + '\n',
      },
      {
        path: 'src/web/tsconfig.json',
        content:
          JSON.stringify(
            {
              extends: './.svelte-kit/tsconfig.json',
              compilerOptions: {
                allowJs: true,
                checkJs: true,
                esModuleInterop: true,
                forceConsistentCasingInFileNames: true,
                resolveJsonModule: true,
                skipLibCheck: true,
                sourceMap: true,
                strict: true,
                moduleResolution: 'bundler',
              },
            },
            null,
            2
          ) + '\n',
      },
      {
        path: 'src/web/svelte.config.js',
        content: `import adapter from '@sveltejs/adapter-static';
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  preprocess: vitePreprocess(),
  kit: {
    adapter: adapter({
      fallback: 'index.html',
    }),
  },
};

export default config;
`,
      },
      {
        path: 'src/web/vite.config.ts',
        content: `import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
  plugins: [sveltekit()],
});
`,
      },
      {
        path: 'src/web/src/app.d.ts',
        content: `// See https://svelte.dev/docs/kit/types#app.d.ts
// for information about these interfaces
declare global {
  namespace App {
    // interface Error {}
    // interface Locals {}
    // interface PageData {}
    // interface PageState {}
    // interface Platform {}
  }
}

export {};
`,
      },
      {
        path: 'src/web/src/app.html',
        content: `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
    %sveltekit.head%
  </head>
  <body>
    <div style="display: contents">%sveltekit.body%</div>
  </body>
</html>
`,
      },
      {
        path: 'src/web/src/routes/+layout.svelte',
        content: `<script lang="ts">
  let { children } = $props();
</script>

{@render children()}
`,
      },
      {
        path: 'src/web/src/routes/+page.svelte',
        content: `<script lang="ts">
  import { onMount } from 'svelte';

  interface Item {
    id: number;
    title: string;
    description: string | null;
    completed: boolean;
  }

  let items = $state<Item[]>([]);
  let loading = $state(true);
  let error = $state<string | null>(null);

  onMount(async () => {
    try {
      const res = await fetch('/api/items');
      if (!res.ok) throw new Error(\`HTTP \${res.status}\`);
      items = await res.json();
    } catch (e) {
      error = e instanceof Error ? e.message : 'Unknown error';
    } finally {
      loading = false;
    }
  });
</script>

<header class="hero">
  <h1>${projectName}</h1>
  <p class="subtitle">Your Azure full-stack app is ready.</p>
  <p class="generated-note">
    Generated by <strong>create-azure-app</strong> — a full-stack template
    preconfigured for Azure deployment with Static Web Apps + Functions + PostgreSQL.
  </p>
</header>

<div class="config-panel">
  <div class="config-card">
    <h2>Project Configuration</h2>
    <div class="config-grid">
      <div class="config-item">
        <span class="config-label">Framework</span>
        <span class="config-value">${config.framework === 'nextjs' ? 'Next.js' : config.framework === 'vite-react' ? 'Vite + React' : 'SvelteKit'}</span>
      </div>
      <div class="config-item">
        <span class="config-label">Database</span>
        <span class="config-value">${config.includeDatabase ? (config.orm === 'prisma' ? 'Prisma' : 'Drizzle') : 'None (mock data)'}</span>
      </div>
      <div class="config-item">
        <span class="config-label">Auth</span>
        <span class="config-value">${config.includeAuth ? 'Yes' : 'No'}</span>
      </div>
      <div class="config-item">
        <span class="config-label">Tailwind</span>
        <span class="config-value">${config.includeTailwind ? 'Yes' : 'No'}</span>
      </div>
      <div class="config-item">
        <span class="config-label">Package Manager</span>
        <span class="config-value">${config.packageManager}</span>
      </div>
    </div>
  </div>
</div>

<div class="content">
  <section class="items-section">
    <h2>Using This Template</h2>
    <p class="items-note">Data in this list is loaded dynamically from your API</p>
    {#if loading}
      <p class="items-status">Loading items...</p>
    {:else if error}
      <p class="items-status items-error">Could not load items: {error}</p>
    {:else if items.length === 0}
      <p class="items-status">No items yet. Run <code>${pmRun(config.packageManager, 'db:seed')}</code> to add sample data.</p>
    {:else}
      <ul class="items-grid">
        {#each items as item (item.id)}
          <li class="item-card">
            <span class="badge {item.completed ? 'badge-done' : 'badge-todo'}">
              {item.completed ? 'Done' : 'Todo'}
            </span>
            <h3>{item.title}</h3>
            {#if item.description}
              <p>{item.description}</p>
            {/if}
          </li>
        {/each}
      </ul>
    {/if}
  </section>
</div>

<style>
  *,
  *::before,
  *::after {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
  }

  :global(body) {
    font-family: 'Plus Jakarta Sans', system-ui, -apple-system, BlinkMacSystemFont,
      'Segoe UI', sans-serif;
    line-height: 1.6;
    color: #1e293b;
    background: #f8fafc;
  }

  /* ── Hero ───────────────────────────────────────────────── */

  .hero {
    background: #0f1729;
    color: #f1f5f9;
    padding: 4rem 2rem 5rem;
    text-align: center;
    position: relative;
  }

  .hero::after {
    content: '';
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
    height: 4px;
    background: linear-gradient(90deg, #0078D4, #00B7C3);
  }

  .hero h1 {
    font-family: 'Plus Jakarta Sans', system-ui, sans-serif;
    font-size: 3.5rem;
    font-weight: 800;
    letter-spacing: -0.025em;
    margin-bottom: 0.5rem;
    background: linear-gradient(135deg, #ffffff 0%, #94a3b8 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
  }

  .hero .subtitle {
    font-size: 1.25rem;
    color: #94a3b8;
    margin-bottom: 1.5rem;
    font-weight: 400;
  }

  .hero .generated-note {
    font-size: 0.875rem;
    color: #64748b;
    max-width: 36rem;
    margin: 0 auto;
    line-height: 1.5;
  }

  .hero .generated-note :global(strong) {
    color: #94a3b8;
  }

  :global(.auth-indicator) {
    position: absolute;
    top: 1rem;
    right: 1.5rem;
    display: flex;
    align-items: center;
    gap: 0.75rem;
    font-size: 0.875rem;
    color: #94a3b8;
  }

  :global(.auth-indicator) :global(a) {
    color: #94a3b8;
    font-size: 0.8125rem;
    opacity: 0.8;
  }

  :global(.auth-indicator) :global(a:hover) {
    opacity: 1;
  }

  /* ── Config Panel ──────────────────────────────────────── */

  .config-panel {
    max-width: 48rem;
    margin: -2rem auto 0;
    padding: 0 1rem;
    position: relative;
    z-index: 1;
  }

  .config-card {
    background: #ffffff;
    border: 1px solid #dbeafe;
    border-radius: 0.75rem;
    padding: 1.5rem 2rem;
    box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.07), 0 2px 4px -2px rgb(0 0 0 / 0.05);
  }

  .config-card h2 {
    font-size: 0.75rem;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: #64748b;
    margin-bottom: 1rem;
  }

  .config-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(8rem, 1fr));
    gap: 1rem;
  }

  .config-item {
    display: flex;
    flex-direction: column;
    gap: 0.125rem;
  }

  .config-label {
    font-size: 0.6875rem;
    font-weight: 500;
    color: #94a3b8;
    text-transform: uppercase;
    letter-spacing: 0.05em;
  }

  .config-value {
    font-size: 0.9375rem;
    font-weight: 600;
    color: #1e293b;
  }

  /* ── Content ───────────────────────────────────────────── */

  .content {
    max-width: 48rem;
    margin: 2.5rem auto 4rem;
    padding: 0 1rem;
  }

  /* ── Items ──────────────────────────────────────────────── */

  .items-section h2 {
    font-size: 1.25rem;
    font-weight: 700;
    color: #1e293b;
    margin-bottom: 0.25rem;
  }

  .items-note {
    color: #64748b;
    font-size: 0.8125rem;
    margin-bottom: 1rem;
  }

  .items-status {
    color: #64748b;
    font-size: 0.875rem;
  }

  .items-error {
    color: #dc2626;
  }

  .items-grid {
    list-style: none;
    display: grid;
    gap: 0.75rem;
  }

  .item-card {
    background: #ffffff;
    border: 1px solid #dbeafe;
    border-radius: 0.5rem;
    padding: 1rem 1.25rem;
    transition: border-color 0.15s ease;
  }

  .item-card:hover {
    border-color: #93c5fd;
  }

  .item-card h3 {
    font-size: 1rem;
    font-weight: 600;
    color: #1e293b;
    margin: 0.25rem 0;
  }

  .item-card p {
    font-size: 0.875rem;
    color: #64748b;
    margin: 0;
  }

  .badge {
    display: inline-block;
    font-size: 0.75rem;
    font-weight: 500;
    padding: 0.125rem 0.5rem;
    border-radius: 9999px;
  }

  .badge-done {
    background: #d1fae5;
    color: #065f46;
  }

  .badge-todo {
    background: #fef3c7;
    color: #92400e;
  }

  a {
    color: #0078D4;
    text-decoration: none;
  }

  a:hover {
    text-decoration: underline;
  }

  code {
    background: #f1f5f9;
    padding: 0.125rem 0.375rem;
    border-radius: 0.25rem;
    font-size: 0.875rem;
    color: #475569;
  }
</style>
`,
      },
    ],
    scripts: {
      'install:web': `cd src/web && ${pmInstall(config.packageManager)}`,
      'dev:web': `cd src/web && ${pmRun(config.packageManager, 'dev')}`,
      'build:web': `cd src/web && ${pmRun(config.packageManager, 'build')}`,
    },
  };
}
