import type { Feature } from '../composer.js';
import type { ProjectConfig } from '../index.js';
import { pmRun, pmInstall } from '../utils.js';

export function viteReactFeature(config: ProjectConfig): Feature {
  const { projectName } = config;

  return {
    name: 'vite-react',
    files: [
      {
        path: 'src/web/package.json',
        content:
          JSON.stringify(
            {
              name: `${projectName}-web`,
              version: '0.1.2',
              private: true,
              type: 'module',
              scripts: {
                dev: 'vite',
                build: 'tsc -b && vite build',
                preview: 'vite preview',
              },
              dependencies: {
                react: '^19.1.0',
                'react-dom': '^19.1.0',
              },
              devDependencies: {
                '@types/react': '^19.1.0',
                '@types/react-dom': '^19.1.0',
                '@vitejs/plugin-react': '^4.4.0',
                typescript: '^5.8.0',
                vite: '^6.3.0',
                ...(config.includeTailwind ? {
                  tailwindcss: '^4.0.0',
                  '@tailwindcss/postcss': '^4.0.0',
                } : {}),
              },
            },
            null,
            2
          ) + '\n',
      },
      {
        path: 'src/web/tsconfig.json',
        content:
          JSON.stringify(
            {
              compilerOptions: {
                target: 'ES2020',
                useDefineForClassFields: true,
                lib: ['ES2020', 'DOM', 'DOM.Iterable'],
                module: 'ESNext',
                skipLibCheck: true,
                moduleResolution: 'bundler',
                allowImportingTsExtensions: true,
                isolatedModules: true,
                moduleDetection: 'force',
                noEmit: true,
                jsx: 'react-jsx',
                strict: true,
                noUnusedLocals: true,
                noUnusedParameters: true,
                noFallthroughCasesInSwitch: true,
              },
              include: ['src'],
            },
            null,
            2
          ) + '\n',
      },
      {
        path: 'src/web/vite.config.ts',
        content: `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  build: {
    outDir: 'dist',
  },
});
`,
      },
      {
        path: 'src/web/index.html',
        content: `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
    <title>${projectName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`,
      },
      {
        path: 'src/web/src/main.tsx',
        content: `import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { App } from './App';
import './App.css';

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
);
`,
      },
      {
        path: 'src/web/src/App.tsx',
        content: `import { useEffect, useState } from 'react';

interface Item {
  id: number;
  title: string;
  description: string | null;
  completed: boolean;
}

export function App() {
  const [items, setItems] = useState<Item[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch('/api/items')
      .then((res) => {
        if (!res.ok) throw new Error(\`HTTP \${res.status}\`);
        return res.json();
      })
      .then((data) => setItems(data))
      .catch((err) => setError(err.message))
      .finally(() => setLoading(false));
  }, []);

  return (
    <>
      <header className="hero">
        <h1>${projectName}</h1>
        <p className="subtitle">Your Azure full-stack app is ready.</p>
        <p className="generated-note">
          Generated by <strong>create-azure-app</strong> — a full-stack template
          preconfigured for Azure deployment with Static Web Apps + Functions + PostgreSQL.
        </p>
      </header>

      <div className="config-panel">
        <div className="config-card">
          <h2>Project Configuration</h2>
          <div className="config-grid">
            <div className="config-item">
              <span className="config-label">Framework</span>
              <span className="config-value">${config.framework === 'nextjs' ? 'Next.js' : config.framework === 'vite-react' ? 'Vite + React' : 'SvelteKit'}</span>
            </div>
            <div className="config-item">
              <span className="config-label">Database</span>
              <span className="config-value">${config.includeDatabase ? (config.orm === 'prisma' ? 'Prisma' : 'Drizzle') : 'None (mock data)'}</span>
            </div>
            <div className="config-item">
              <span className="config-label">Auth</span>
              <span className="config-value">${config.includeAuth ? 'Yes' : 'No'}</span>
            </div>
            <div className="config-item">
              <span className="config-label">Tailwind</span>
              <span className="config-value">${config.includeTailwind ? 'Yes' : 'No'}</span>
            </div>
            <div className="config-item">
              <span className="config-label">Package Manager</span>
              <span className="config-value">${config.packageManager}</span>
            </div>
          </div>
        </div>
      </div>

      <div className="content">
        <section className="items-section">
          <h2>Using This Template</h2>
          <p className="items-note">Data in this list is loaded dynamically from your API</p>
          {loading && <p className="items-status">Loading items...</p>}
          {error && (
            <p className="items-status items-error">Could not load items: {error}</p>
          )}
          {!loading && !error && items.length === 0 && (
            <p className="items-status">
              No items yet. Run <code>${pmRun(config.packageManager, 'db:seed')}</code> to add sample data.
            </p>
          )}
          {items.length > 0 && (
            <ul className="items-grid">
              {items.map((item) => (
                <li key={item.id} className="item-card">
                  <span
                    className={\`badge \${
                      item.completed ? 'badge-done' : 'badge-todo'
                    }\`}
                  >
                    {item.completed ? 'Done' : 'Todo'}
                  </span>
                  <h3>{item.title}</h3>
                  {item.description && <p>{item.description}</p>}
                </li>
              ))}
            </ul>
          )}
        </section>
      </div>
    </>
  );
}
`,
      },
      {
        path: 'src/web/src/App.css',
        content: `*,
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

body {
  font-family: 'Plus Jakarta Sans', system-ui, -apple-system, BlinkMacSystemFont,
    'Segoe UI', sans-serif;
  line-height: 1.6;
  color: #1e293b;
  background: #f8fafc;
}

/* ── Hero ─────────────────────────────────────────────────── */

.hero {
  background: #0f1729;
  color: #f1f5f9;
  padding: 4rem 2rem 5rem;
  text-align: center;
  position: relative;
}

.hero::after {
  content: '';
  position: absolute;
  bottom: 0;
  left: 0;
  right: 0;
  height: 4px;
  background: linear-gradient(90deg, #0078D4, #00B7C3);
}

.hero h1 {
  font-family: 'Plus Jakarta Sans', system-ui, sans-serif;
  font-size: 3.5rem;
  font-weight: 800;
  letter-spacing: -0.025em;
  margin-bottom: 0.5rem;
  background: linear-gradient(135deg, #ffffff 0%, #94a3b8 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

.hero .subtitle {
  font-size: 1.25rem;
  color: #94a3b8;
  margin-bottom: 1.5rem;
  font-weight: 400;
}

.hero .generated-note {
  font-size: 0.875rem;
  color: #64748b;
  max-width: 36rem;
  margin: 0 auto;
  line-height: 1.5;
}

.hero .generated-note strong {
  color: #94a3b8;
}

.auth-indicator {
  position: absolute;
  top: 1rem;
  right: 1.5rem;
  display: flex;
  align-items: center;
  gap: 0.75rem;
  font-size: 0.875rem;
  color: #94a3b8;
}

.auth-indicator a {
  color: #94a3b8;
  font-size: 0.8125rem;
  opacity: 0.8;
}

.auth-indicator a:hover {
  opacity: 1;
}

/* ── Config Panel ────────────────────────────────────────── */

.config-panel {
  max-width: 48rem;
  margin: -2rem auto 0;
  padding: 0 1rem;
  position: relative;
  z-index: 1;
}

.config-card {
  background: #ffffff;
  border: 1px solid #dbeafe;
  border-radius: 0.75rem;
  padding: 1.5rem 2rem;
  box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.07), 0 2px 4px -2px rgb(0 0 0 / 0.05);
}

.config-card h2 {
  font-size: 0.75rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: #64748b;
  margin-bottom: 1rem;
}

.config-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(8rem, 1fr));
  gap: 1rem;
}

.config-item {
  display: flex;
  flex-direction: column;
  gap: 0.125rem;
}

.config-label {
  font-size: 0.6875rem;
  font-weight: 500;
  color: #94a3b8;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.config-value {
  font-size: 0.9375rem;
  font-weight: 600;
  color: #1e293b;
}

/* ── Content ─────────────────────────────────────────────── */

.content {
  max-width: 48rem;
  margin: 2.5rem auto 4rem;
  padding: 0 1rem;
}

/* ── Items ────────────────────────────────────────────────── */

.items-section h2 {
  font-size: 1.25rem;
  font-weight: 700;
  color: #1e293b;
  margin-bottom: 0.25rem;
}

.items-note {
  color: #64748b;
  font-size: 0.8125rem;
  margin-bottom: 1rem;
}

.items-status {
  color: #64748b;
  font-size: 0.875rem;
}

.items-error {
  color: #dc2626;
}

.items-grid {
  list-style: none;
  display: grid;
  gap: 0.75rem;
}

.item-card {
  background: #ffffff;
  border: 1px solid #dbeafe;
  border-radius: 0.5rem;
  padding: 1rem 1.25rem;
  transition: border-color 0.15s ease;
}

.item-card:hover {
  border-color: #93c5fd;
}

.item-card h3 {
  font-size: 1rem;
  font-weight: 600;
  color: #1e293b;
  margin: 0.25rem 0;
}

.item-card p {
  font-size: 0.875rem;
  color: #64748b;
  margin: 0;
}

.badge {
  display: inline-block;
  font-size: 0.75rem;
  font-weight: 500;
  padding: 0.125rem 0.5rem;
  border-radius: 9999px;
}

.badge-done {
  background: #d1fae5;
  color: #065f46;
}

.badge-todo {
  background: #fef3c7;
  color: #92400e;
}

a {
  color: #0078D4;
  text-decoration: none;
}

a:hover {
  text-decoration: underline;
}

code {
  background: #f1f5f9;
  padding: 0.125rem 0.375rem;
  border-radius: 0.25rem;
  font-size: 0.875rem;
  color: #475569;
}
`,
      },
    ],
    scripts: {
      'install:web': `cd src/web && ${pmInstall(config.packageManager)}`,
      'dev:web': `cd src/web && ${pmRun(config.packageManager, 'dev')}`,
      'build:web': `cd src/web && ${pmRun(config.packageManager, 'build')}`,
    },
  };
}
